import { Router, type IRouter } from "express";
import healthRouter from "./health";
import vehiclesRouter from "./vehicles";
import leadsRouter from "./leads";
import customersRouter from "./customers";
import dealsRouter from "./deals";
import appraisalsRouter from "./appraisals";
import financeRouter from "./finance";
import serviceRouter from "./service";
import agentsRouter from "./agents";
import activityRouter from "./activity";
import dashboardRouter from "./dashboard";
import timelineRouter from "./timeline";
import gatesRouter from "./gates";
import anthropicRouter from "./anthropic";
import copilotkitRouter from "./copilotkit";
import graRouter from "./gra";
import pipelineRouter from "./pipeline";

const router: IRouter = Router();

router.use(healthRouter);
router.use(vehiclesRouter);
router.use(leadsRouter);
router.use(customersRouter);
router.use(dealsRouter);
router.use(appraisalsRouter);
router.use(financeRouter);
router.use(serviceRouter);
router.use(agentsRouter);
router.use(activityRouter);
router.use(dashboardRouter);
router.use(timelineRouter);
router.use(gatesRouter);
router.use(anthropicRouter);
router.use(copilotkitRouter);
router.use(graRouter);
router.use(pipelineRouter);

export default router;
